[project]
name = "traacer"
authors = [
    {name = "Kasimir Stadie", email = "kstadie@ethz.ch"}
]
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "sounddevice",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "av",
    "cryptography",
    "websockets",
    "qrcode[pil]",
    "scipy",
    "matplotlib"
]
